name: "using composite"
run-name: one of the file

on:
  workflow_dispatch:
      
    

jobs:
  compile-status:
    runs-on: ubuntu-latest
    outputs:
      state: ${{steps.states.outputs.state}}
    steps:
      - uses: actions/checkout@v4

      - uses: Saikiranreddy-dev/microservice-workflows@v1
        id: states
        with:
          from-date: "2024-01-01"

      - name: "printing the states"
        env:
          stateful: state
        run: |
          echo $stateful
          
  
