name: lesson2_excercise3

run-name: run of file when it reruns more than 2 times

on: 
  workflow_dispatch: 
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: prevent reruns
        run : |
          if [ "$RUN_ATTEMPT_NUMBER" -gt "$MAXIMUM_ATTEMPTS"]; then
            echo "Exiting because the run number is greater than the matrix number of attempts"
            exit 1
          fi
        env:
          MAXIMUM_ATTEMPTS: ${{vars.MAXIMUM_ATTEMPTS}}
          RUN_ATTEMPT_NUMBER: ${{github.run_attempt}}
      - name: run job
        run: |
          echo "Running job"
          sleep 1;
            
        
      
