name: expression 
run-name: running an expression file
on: 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: experimenting
        run: |
            echo $Hello
            echo $true
            echo $event
        env:
          Hello: ${{'hello'}} world saikiran
          true: ${{1==2}}
          event: ${{github.event_name}}
      
