name: functions

run-name: running a function file

on: 
  workflow_dispatch:
    
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: experimenting
        run: |
            echo $contains
            echo $format
            printf "$tojson"
        env:
          contains: ${{ contains('github events','Evecolonts')}}
          format: ${{ format('this is {0}{1}','too','cool')}}
          tojson: ${{toJSON(github)}}
          
