name: workflow

run-name: run of workflow commands file

on: 
  issues:
    types: 
      - opened

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - name: add comment
        run: |
          gh  issue comment "Number" --body "$Body"
        env:
          GH_TOKEN: ${{secrets.token}}
          GH_REPO: ${{github.repository}}
          Number: ${{github.event.issue.number}}
          Body: >
            :sparkles: thankyou raising an issue :sparkles:
          
          
