name: buiding issueChecker

run-name: run of issue workflow

on: 
  issues: 
    types: [opened]

permissions: 
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: executes only when the issue is opened
        env:
          ISSUE_NUMBER: ${{github.event.issue.number}}
        uses: actions/github-script@v7
        with:
          script: |
            const { ISSUE_NUMBER } = process.env;
            await github.rest.issues.createComment({
              owner:context.repo.owner,
              repo:context.repo.repo,
              body:"thanks for opening this issue"+ISSUE_NUMBER
            });
      
       
      
