name: lesson 1 -exercise 3

run-name: run of complex workflow

on: 
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a single line script
        run : echo "Hello World !"
      - name: Run a Multi line script
        run : |
            echo "add other actions to build",
            echo test, and deploy your project.
      -uses: actions/setup-node@v6
      with:
          node-version: 24
      -run: npm ci
      -run: npm test
      
