name: reusable-workflow
run-name: running a called workflow

on:
  push:
  pull_request: 
  workflow_dispatch:
    inputs:
      variable:
        description: "enter any option"
        type: choice
        options:
          - regression
          - smoke
        default: regression
        required: true
  
jobs:
  test:
    uses: Saikiranreddy-dev/microservice-workflows/.github/workflows/microservice-ci.yml@main
    secrets: 
      token: ${{secrets.token}}
      variable: ${{vars.variable}}
    with:
      variable1: ${{vars.variable}}
        
  
