name: reusable-workflow
run-name: running a called workflow

on:
  push:
  pull_request: 
  workflow_dispatch:
  
jobs:
  test:
    uses: Saikiranreddy-dev/microservice-workflows/.github/workflows/microservice-ci.yml@main
    secrets: 
      token: ${{secrets.GITHUB_TOKEN}}
        
  
