name: variables_and_secrets

run-name: running a variables_and_secrets file

on: 
  workflow_dispatch:
    
  

jobs:
  variable:
    runs-on: ubuntu-latest
    steps:
      - name: experimenting
        run: |
            echo $repovariable
        env:
            repovariable: ${{vars.repo_variable}}
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: experimenting
        run: |
            echo $secretvariable
        env:
            secretvariable: ${{secrets.REPO_SECRETS}}
  
